<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh">
<context>
    <name>ChineseAIAssistant</name>
    <message>
        <location filename="../chinese_ai_assistant.py" line="204"/>
        <source>&amp;Chinese AI Assistant</source>
        <translation>&amp;中文AI助手</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant.py" line="173"/>
        <source>Chinese AI Assistant</source>
        <translation>中文AI助手</translation>
    </message>
</context>
<context>
    <name>ChineseAIAssistantDockWidget</name>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget.py" line="79"/>
        <source>**Question:</source>
        <translation>**问题：</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget.py" line="80"/>
        <source>**Answer:</source>
        <translation>**回答：</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget.py" line="106"/>
        <source>Stop</source>
        <translation>停止</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget.py" line="150"/>
        <source>Send</source>
        <translation>发送</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget.py" line="131"/>
        <source>**No reference documents can be found in [Phienix-GIS](https://www.phoenix-gis.cn) knowledge db. The content below is generated by an LLM. Please review it carefully.**

</source>
        <translation type="obsolete">在[凤凰地理社区](https://www.phoenix-gis.cn)知识库中没有找到相关内容。以下内容均由大模型生成。请谨慎辨别。\n\n</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget.py" line="133"/>
        <source>**The content below is based on [Phienix-GIS](https://www.phoenix-gis.cn) knowledge db.**

</source>
        <translation type="obsolete">以下内容基于[凤凰地理社区](https://www.phoenix-gis.cn)知识库生成。\n\n</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget.py" line="131"/>
        <source>**No reference documents can be found in [Phienix-GIS](https://www.phoenix-gis.cn) knowledge db. The content below is generated by an LLM. Please review it carefully.**</source>
        <translation type="obsolete">**在[凤凰地理社区](https://www.phoenix-gis.cn)知识库中没有找到相关内容。以下内容均由通用大模型生成。请谨慎辨别。**</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget.py" line="133"/>
        <source>**The content below is based on [Phienix-GIS](https://www.phoenix-gis.cn) knowledge db.**</source>
        <translation type="obsolete">**以下内容基于[凤凰地理社区](https://www.phoenix-gis.cn)知识库生成。**</translation>
    </message>
</context>
<context>
    <name>ChineseAIAssistantDockWidgetBase</name>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget_base.ui" line="19"/>
        <source>Chinese AI Assistant</source>
        <translation>中文AI助手</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget_base.ui" line="54"/>
        <source>Chatbot:</source>
        <translation>对话：</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget_base.ui" line="81"/>
        <source>My Question:</source>
        <translation>问题：</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget_base.ui" line="120"/>
        <source>Settings</source>
        <translation>设置</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget_base.ui" line="147"/>
        <source>Send</source>
        <translation>发送</translation>
    </message>
    <message>
        <location filename="../chinese_ai_assistant_dockwidget_base.ui" line="154"/>
        <source>Clear</source>
        <translation>清除</translation>
    </message>
</context>
<context>
    <name>DlgSetting</name>
    <message>
        <location filename="../setting_dialog.ui" line="14"/>
        <source>Chinese AI Assistant Setting</source>
        <translation>中文AI助手设置</translation>
    </message>
    <message>
        <location filename="../setting_dialog.ui" line="44"/>
        <source>Apply for high-speed channel. Please enter your email address and click &apos;Apply&apos;. We will contact you via email within 24 hours. </source>
        <translation type="unfinished">申请专用高速通道，请输入您的电子邮箱地址后，点击&quot;申请&quot;按钮。我们将会在24小时内发送邮件给您。请注意查收。</translation>
    </message>
    <message>
        <location filename="../setting_dialog.ui" line="56"/>
        <source>E-mail：</source>
        <translation>电子邮件：</translation>
    </message>
    <message>
        <location filename="../setting_dialog.ui" line="83"/>
        <source>Apply</source>
        <translation>申请</translation>
    </message>
    <message>
        <location filename="../setting_dialog.ui" line="90"/>
        <source>OK</source>
        <translation>确认</translation>
    </message>
</context>
<context>
    <name>SettingDialog</name>
    <message>
        <location filename="../setting_dialog.py" line="73"/>
        <source>Warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <location filename="../setting_dialog.py" line="67"/>
        <source>Please enter your email address.</source>
        <translation>请输入您的电子邮箱地址。</translation>
    </message>
    <message>
        <location filename="../setting_dialog.py" line="73"/>
        <source>Please enter a valid email address.</source>
        <translation>请输入正确的电子邮箱地址。</translation>
    </message>
    <message>
        <location filename="../setting_dialog.py" line="88"/>
        <source>Tip</source>
        <translation>提示</translation>
    </message>
    <message>
        <location filename="../setting_dialog.py" line="88"/>
        <source>Your request has been received. We&apos;ll get back to you by email within 24 hours. Please check your inbox later.</source>
        <translation>您的申请已送达，我们将会在24小时内回复您。请稍后查收。</translation>
    </message>
    <message>
        <location filename="../setting_dialog.py" line="98"/>
        <source>Error</source>
        <translation>错误</translation>
    </message>
    <message>
        <location filename="../setting_dialog.py" line="93"/>
        <source>Failed to submit your request. Please try again later.</source>
        <translation>无法提交您的申请。请稍后再试。</translation>
    </message>
    <message>
        <location filename="../setting_dialog.py" line="98"/>
        <source>Network error. Please check your connection and try again.</source>
        <translation>网络错误：请检查您的网络连接后，再次尝试。</translation>
    </message>
</context>
<context>
    <name>StreamChatWorker</name>
    <message>
        <location filename="../stream_chat_worker.py" line="75"/>
        <source>Network Error:</source>
        <translation>网络错误：</translation>
    </message>
</context>
</TS>
